// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutvW8LtVPW_yc68s7LkSTEh24m6uQfv8',
    appId: '1:13107465713:web:d8e3bbf83f01edb5850850',
    messagingSenderId: '13107465713',
    projectId: 'motivosprateamar-44453',
    authDomain: 'motivosprateamar-44453.firebaseapp.com',
    databaseURL: 'https://motivosprateamar-44453-default-rtdb.firebaseio.com',
    storageBucket: 'motivosprateamar-44453.appspot.com',
    measurementId: 'G-60C6HMS4W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALqur0Mj0_CxSQLb6u14IkXv3focEdtsc',
    appId: '1:13107465713:android:1d1fdb619bd35334850850',
    messagingSenderId: '13107465713',
    projectId: 'motivosprateamar-44453',
    databaseURL: 'https://motivosprateamar-44453-default-rtdb.firebaseio.com',
    storageBucket: 'motivosprateamar-44453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8BdBAcwdkX4y26lL1iXYxIun1NKb-LE',
    appId: '1:13107465713:ios:80df8eddb833f93c850850',
    messagingSenderId: '13107465713',
    projectId: 'motivosprateamar-44453',
    databaseURL: 'https://motivosprateamar-44453-default-rtdb.firebaseio.com',
    storageBucket: 'motivosprateamar-44453.appspot.com',
    iosClientId: '13107465713-pp8hs7d35f5q8jav98gp0d1iqldupsvn.apps.googleusercontent.com',
    iosBundleId: 'com.xXFalcoonXx.motivosprateamar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ8BdBAcwdkX4y26lL1iXYxIun1NKb-LE',
    appId: '1:13107465713:ios:80df8eddb833f93c850850',
    messagingSenderId: '13107465713',
    projectId: 'motivosprateamar-44453',
    databaseURL: 'https://motivosprateamar-44453-default-rtdb.firebaseio.com',
    storageBucket: 'motivosprateamar-44453.appspot.com',
    iosClientId: '13107465713-pp8hs7d35f5q8jav98gp0d1iqldupsvn.apps.googleusercontent.com',
    iosBundleId: 'com.xXFalcoonXx.motivosprateamar',
  );
}
